version: '3.8'

services:
    db:
        build: ./docker/mysql
        ports:
            - "33306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: testdb
        volumes: 
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
    php:
        build: ./docker/php
        ports: 
            - "8080:80"
        volumes: 
            - ./src:/var/www
        depends_on: 
            - db
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5
        container_name: phpmyadmin
        links: 
            - db
        ports: 
            - 8081:80
        volumes:
            - ./docker/phpmyadmin/sessions:/sessions
